namespace: default

docker:
  repository: nhan925

ingress:
  name: spring-petclinic-ingress
  host: petclinic.cloud
  serviceName: api-gateway
  servicePort: 8080

services:
  config-server:
    ports:
      port: 8888
      targetPort: 8888
    image:
      name: spring-petclinic-config-server

  discovery-server:
    ports:
      port: 8761
      targetPort: 8761
    image:
      name: spring-petclinic-discovery-server

  admin-server:
    ports:
      port: 9090
      targetPort: 9090
    image:
      name: spring-petclinic-admin-server

  customers-service:
    ports:
      port: 8081
      targetPort: 8081
    image:
      name: spring-petclinic-customers-service

  visits-service:
    ports:
      port: 8082
      targetPort: 8082
    image:
      name: spring-petclinic-visits-service

  vets-service:
    ports:
      port: 8083
      targetPort: 8083
    image:
      name: spring-petclinic-vets-service

  genai-service:
    ports:
      port: 8084
      targetPort: 8084
    image:
      name: spring-petclinic-genai-service

  api-gateway:
    ports:
      port: 8080
      targetPort: 8080
    image:
      name: spring-petclinic-api-gateway

  tracing-server:
    dockerRepository: openzipkin
    ports:
      port: 9411
      targetPort: 9411
    image:
      name: zipkin
    env:
      - name: JAVA_OPTS
        value: "-XX:UseSVE=0"
 