apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pet-clinic-staging
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/nhan925/devops_lab02_k8s.git' # Replace with your Git repository URL
    targetRevision: HEAD                # Replace with the branch or tag to deploy
    path: .        # Path to the Helm chart in the repository
    helm:
      valueFiles:
        - values.yaml                   # Default values
        - environments/values-staging.yaml  # Dev-specific overrides

  destination:
    server: 'https://kubernetes.default.svc' # Kubernetes cluster API server
    namespace: staging                          # Namespace for the dev environment

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true