apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pet-clinic-staging
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/MaThanhNhi/spring-petclinic-microservices.git' # Replace with your Git repository URL
    targetRevision: HEAD                # Replace with the branch or tag to deploy
    path: .        # Path to the Helm chart in the repository
    helm:
      valueFiles:
        - values.yaml                   # Default values
        - environments/values-dev.yaml  # Dev-specific overrides

  destination:
    server: 'https://kubernetes.default.svc' # Kubernetes cluster API server
    namespace: staging                          # Namespace for the dev environment

  syncPolicy:
    automated:
      prune: true
      selfHeal: true