namespace: staging
imagePullPolicy: IfNotPresent

imageTag: &tag v1.0.0

services:
  - name: spring-petclinic-config-server
    image:
      tag: *tag
  - name: spring-petclinic-discovery-server
    image:
      tag: *tag
  - name: spring-petclinic-admin-server
    image:
      tag: *tag
  - name: spring-petclinic-customers-service
    image:
      tag: *tag
  - name: spring-petclinic-visits-service
    image:
      tag: *tag
  - name: spring-petclinic-vets-service
    image:
      tag: *tag
  - name: spring-petclinic-genai-service
    image:
      tag: *tag
  - name: spring-petclinic-api-gateway
    image:
      tag: *tag
    ports:
      nodePort: 30081
