{{- range $name, $service := .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
  namespace: {{ $.Values.namespace }}
spec:
  revisionHistoryLimit: 2
  replicas: 2
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      {{- if $service.dependOn }}
      initContainers:
        - name: init-container-for-{{ $name }}
          image: curlimages/curl:latest
          command:
            - sh
            - -c
            - >
              until curl -sf http://{{ $service.dependOn.name }}:{{ $service.dependOn.port }}/actuator/health;
              do echo "waiting for {{ $service.dependOn.name }}..."; sleep 5;
              done
      {{- end }}
      containers:
        - name: {{ $name }}
          image: "{{ $service.dockerRepository | default $.Values.docker.repository }}/{{ $service.image.name }}:{{ $service.image.tag | default "latest" }}"
          imagePullPolicy: "{{ $.Values.imagePullPolicy | default "Always"}}"
          ports:
            - containerPort: {{ $service.ports.targetPort | default 0 }}
          {{- if $service.env }}
          env:
            {{- toYaml $service.env | nindent 12 }}
            - name: EUREKA_INSTANCE_HOSTNAME
              value: {{ $name }}
          {{- end }}
          {{- if $service.readinessProbe }}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ $service.ports.targetPort | default 0 }}
            initialDelaySeconds: {{ $service.readinessProbe.initialDelaySeconds | default 30 }}
            periodSeconds: {{ $service.readinessProbe.periodSeconds | default 10 }}
            failureThreshold: {{ $service.readinessProbe.failureThreshold | default 10 }}
            successThreshold: {{ $service.readinessProbe.successThreshold | default 1 }}
          {{- end }}
---
{{- end }}