{{- range $name, $service := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
  namespace: {{ $.Values.namespace }}
spec:
  type: {{ $service.type | default "ClusterIP" }}   # Default to ClusterIP if not set in values.yaml
  selector:
    app: {{ $name }}
  ports:
    - protocol: TCP
      port: {{ $service.ports.port }}         # Exposed port inside the cluster
      targetPort: {{ $service.ports.targetPort | default 0 }}   # Container port
      {{- if eq $service.type "NodePort" }}
      nodePort: {{ $service.ports.nodePort }}  # Only define nodePort if the service type is NodePort
      {{- end }}
---
{{- end }}
